---
- hosts: ansible_lab
  become: yes
  tasks:
    - name: install httpd in two servers
      yum:
        name: httpd
        state: latest
    - name: enabled httpd service
      service:
        name: httpd
        enabled: yes
    - name: Start httpd service in two servers
      service:
        name: httpd
        state: started
    - name: create a file in /var/www/html/index.html
      file:
        path: "/var/www/html/index.html"
        state: touch
    - name: write coneten in /var/www/html/index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Hello from ansible</h1>"