---
#tasks

- name: install httpd
  yum:
    name: httpd
    state: latest

- name: copy configuration file
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart httpd service

- name: enable and start httpd
  service:
    name: httpd
    enabled: yes
    state: started