---
# tasks file for php-install
- name: install php7.3
  yum:
    name:
        - php
        - php-common
        - php-opcache 
        - php-mcrypt 
        - php-cli 
        - php-gd 
        - php-curl 
        - php-mysqlnd 
  notify: restart httpd service